-- MySQL Script generated by MySQL Workbench
-- Sat Oct 31 17:00:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SUCV
-- -----------------------------------------------------
-- Sistema Unico de Control Vacacional

-- -----------------------------------------------------
-- Schema SUCV
--
-- Sistema Unico de Control Vacacional
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SUCV` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `SUCV` ;

-- -----------------------------------------------------
-- Table `SUCV`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SUCV`.`USER` ;

CREATE TABLE IF NOT EXISTS `SUCV`.`USER` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'User id to store the user info',
  `name` VARCHAR(60) NOT NULL,
  `dni` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUCV`.`ESTABLISHMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SUCV`.`ESTABLISHMENT` ;

CREATE TABLE IF NOT EXISTS `SUCV`.`ESTABLISHMENT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUCV`.`HOUSE_PLACE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SUCV`.`HOUSE_PLACE` ;

CREATE TABLE IF NOT EXISTS `SUCV`.`HOUSE_PLACE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUCV`.`USER_VACATIONAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SUCV`.`USER_VACATIONAL` ;

CREATE TABLE IF NOT EXISTS `SUCV`.`USER_VACATIONAL` (
  `id` INT NOT NULL,
  `birthday` DATE NOT NULL,
  `borncity` INT NOT NULL,
  `childcharge` INT NULL,
  `email` VARCHAR(45) NULL,
  `imageUrl` VARCHAR(1000) NULL,
  `provider` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_id_user_vacational`
    FOREIGN KEY (`id`)
    REFERENCES `SUCV`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUCV`.`USER_ESTABLISHMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SUCV`.`USER_ESTABLISHMENT` ;

CREATE TABLE IF NOT EXISTS `SUCV`.`USER_ESTABLISHMENT` (
  `id` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_establishment` INT NOT NULL,
  `date_in` TIMESTAMP NOT NULL,
  `date_out` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_establishment_idx` (`id_establishment` ASC) VISIBLE,
  INDEX `fk_id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_id_user_establishment`
    FOREIGN KEY (`id_user`)
    REFERENCES `SUCV`.`USER_VACATIONAL` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_establishment`
    FOREIGN KEY (`id_establishment`)
    REFERENCES `SUCV`.`ESTABLISHMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUCV`.`USER_PLACE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SUCV`.`USER_PLACE` ;

CREATE TABLE IF NOT EXISTS `SUCV`.`USER_PLACE` (
  `id` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_place` INT NOT NULL,
  `date_in` DATE NOT NULL,
  `date_out` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_house_place_idx` (`id_place` ASC) VISIBLE,
  INDEX `fk_id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_id_user_place`
    FOREIGN KEY (`id_user`)
    REFERENCES `SUCV`.`USER_VACATIONAL` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_house_place`
    FOREIGN KEY (`id_place`)
    REFERENCES `SUCV`.`HOUSE_PLACE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUCV`.`USER_PERSONAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SUCV`.`USER_PERSONAL` ;

CREATE TABLE IF NOT EXISTS `SUCV`.`USER_PERSONAL` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_id_user_personal`
    FOREIGN KEY (`id`)
    REFERENCES `SUCV`.`USER` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `SUCV`.`USER`
-- -----------------------------------------------------
START TRANSACTION;
USE `SUCV`;
INSERT INTO `SUCV`.`USER` (`id`, `name`, `dni`) VALUES (1, 'Maxi Roselli', 35130194);
INSERT INTO `SUCV`.`USER` (`id`, `name`, `dni`) VALUES (2, 'Florencia Roselli', 37874111);
INSERT INTO `SUCV`.`USER` (`id`, `name`, `dni`) VALUES (3, 'Magali Rebolli', 37731944);

COMMIT;


-- -----------------------------------------------------
-- Data for table `SUCV`.`USER_VACATIONAL`
-- -----------------------------------------------------
START TRANSACTION;
USE `SUCV`;
INSERT INTO `SUCV`.`USER_VACATIONAL` (`id`, `birthday`, `borncity`, `childcharge`, `email`, `imageUrl`, `provider`) VALUES (2, '08/08/1990', 1, 0, 'florenciaroselli@gmail.com', NULL, 'MANUAL');
INSERT INTO `SUCV`.`USER_VACATIONAL` (`id`, `birthday`, `borncity`, `childcharge`, `email`, `imageUrl`, `provider`) VALUES (3, '23/03/1994', 2, 0, 'magalirebollo@gmail.com', NULL, 'MANUAL');

COMMIT;


-- -----------------------------------------------------
-- Data for table `SUCV`.`USER_PERSONAL`
-- -----------------------------------------------------
START TRANSACTION;
USE `SUCV`;
INSERT INTO `SUCV`.`USER_PERSONAL` (`id`) VALUES (1);

COMMIT;

